server:
  port: 8080
  allowOrigins:
    - "*"
  bodyLimit: "10M" # MiB
  timeout: 30 # Seconds

database:
  host: localhost
  port: 5432
  user: your_users
  password: your_password
  dbname: your_dbname
  sslmode: disable
  schema: public
